# Generated by Django 2.2.5 on 2019-09-13 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizacion',
            options={'verbose_name_plural': 'organizaciones'},
        ),
    ]
