# Generated by Django 2.2.5 on 2019-09-13 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='cuenta',
            new_name='organizacion',
        ),
    ]
