# Generated by Django 2.2.5 on 2019-09-16 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20190913_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donante',
            fields=[
                ('contacto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.Contacto')),
                ('cuentaBanco', models.CharField(max_length=22)),
            ],
            bases=('crm.contacto',),
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('contacto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.Contacto')),
                ('barrio', models.CharField(max_length=50)),
            ],
            bases=('crm.contacto',),
        ),
    ]
