# Generated by Django 2.2.5 on 2019-10-07 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20191007_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='cuenta',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Cuenta'),
        ),
    ]
