# Generated by Django 2.2.5 on 2019-10-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20191007_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='fecha_de_nacimiento',
            field=models.DateField(verbose_name='fecha de nacimiento'),
        ),
    ]
