# Generated by Django 2.2.5 on 2019-10-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20191019_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donante',
            name='fecha_de_baja',
            field=models.DateField(verbose_name='fecha de baja'),
        ),
        migrations.AlterField(
            model_name='donante',
            name='fecha_de_compromiso',
            field=models.DateField(verbose_name='fecha de compromiso'),
        ),
    ]
