# Generated by Django 2.2.5 on 2019-10-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20191019_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacion',
            name='fecha_alta',
            field=models.DateField(verbose_name='fecha de alta'),
        ),
    ]
