# Generated by Django 2.2.5 on 2019-10-19 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20191019_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='sexo',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CampoSexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Organizacion')),
            ],
        ),
    ]
