# Generated by Django 2.2.5 on 2019-10-19 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20191019_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='sexo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm.CampoSexo'),
        ),
    ]
