# Generated by Django 2.2.5 on 2019-10-19 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20191019_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='sexo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.CampoSexo'),
        ),
    ]
