# Generated by Django 2.2.5 on 2019-10-21 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20191019_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoCustomGenero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Organizacion')),
            ],
        ),
        migrations.RenameModel(
            old_name='CampoSexo',
            new_name='CampoCustomOrigen',
        ),
        migrations.RenameField(
            model_name='campocustomorigen',
            old_name='sexo',
            new_name='origen',
        ),
        migrations.AddField(
            model_name='contacto',
            name='origen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.CampoCustomOrigen'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='sexo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.CampoCustomGenero'),
        ),
        migrations.CreateModel(
            name='CampoCustomTipoCuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Organizacion')),
            ],
        ),
        migrations.CreateModel(
            name='CampoCustomTipoContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Organizacion')),
            ],
        ),
        migrations.AddField(
            model_name='contacto',
            name='categoria',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.CampoCustomTipoContacto'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='tipo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.CampoCustomTipoCuenta'),
        ),
    ]
