# Generated by Django 2.2.5 on 2019-10-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20191021_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voluntario',
            name='dias_que_participa',
        ),
        migrations.AddField(
            model_name='voluntario',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(0, 'Activo'), (1, 'Inactivo')], null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(0, 'General'), (1, 'Donante'), (2, 'Voluntario'), (3, 'Ambos')], default=0, null=True, verbose_name='Tipo de Contacto'),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='habilidades',
            field=models.IntegerField(blank=True, choices=[(0, 'Informatica'), (1, 'Electricidad'), (2, 'Carpinteria'), (3, 'Otras')], null=True),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='turno',
            field=models.IntegerField(blank=True, choices=[(0, 'Mañana'), (1, 'Tarde')], null=True),
        ),
    ]
