# Generated by Django 2.2.5 on 2019-10-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_auto_20191022_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='nombre',
            field=models.CharField(default=None, max_length=200, unique=True),
        ),
    ]
