# Generated by Django 2.2.5 on 2019-10-28 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_auto_20191027_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='documento',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='nombre',
            field=models.CharField(default=None, max_length=200, unique=True),
        ),
    ]
