# Generated by Django 2.2.5 on 2019-10-31 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_auto_20191031_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campocustomtipooportunidad',
            old_name='estado',
            new_name='tipo',
        ),
    ]
