# Generated by Django 2.2.5 on 2019-10-31 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_auto_20191031_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='calle',
            new_name='direccion',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='numero',
        ),
        migrations.AddField(
            model_name='organizacion',
            name='tyc_leido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='pais',
            field=models.IntegerField(blank=True, choices=[(0, 'Argentina'), (1, 'Ecuador'), (2, 'Peru'), (3, 'Venezuela'), (4, 'Mexico'), (5, 'Panama'), (6, 'Chile'), (7, 'Uruguay')], default=None, null=True),
        ),
    ]
