# Generated by Django 2.2.5 on 2019-11-03 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_auto_20191031_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.CampoCustomTipoContacto'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.CampoCustomOrigen'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.CampoCustomTipoCuenta'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='estado_oportunidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.CampoCustomEstadoOportunidad'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.CampoCustomTipoOportunidad'),
        ),
    ]
