# Generated by Django 2.2.5 on 2019-11-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_auto_20191103_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='fecha_de_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento'),
        ),
    ]
