# Generated by Django 2.2.5 on 2019-11-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_auto_20191104_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='nombre',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='cuenta',
            unique_together={('organizacion', 'nombre')},
        ),
    ]
