# Generated by Django 2.2.5 on 2019-11-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_auto_20191104_1612'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cuenta',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='cuenta',
            constraint=models.UniqueConstraint(fields=('organizacion', 'nombre'), name='nombre_cuenta_unica'),
        ),
    ]
