# Generated by Django 2.2.5 on 2019-11-29 15:54

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_auto_20191125_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donante',
            name='monto',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='ARS', max_digits=14),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='monto',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='ARS', max_digits=14),
        ),
    ]
